package it.eng.clearinghouse.chaincode;

/**
 * @author Antonio Scatoloni on 09/12/2020
 **/

public class TimezoneRemover {

    public static String removeTimezoneFromIssued(String objectJson) {
        // 2020-08-27T09:30:41.962UTC -> 2020-08-27T09:30:41.962Z
        // The first one is generated by jackson problems with Timezone!!!
        String[] lines = objectJson.split(System.lineSeparator());
        if (null != lines && lines.length > 0) {
            for (String line : lines) {
                if (line.contains("ids:issued") && line.contains("UTC")) {
                    String originalLine = line;
                    line = line.replaceAll("UTC", "Z");
                    objectJson = objectJson.replace(originalLine, line);
                }
            }
        }
        return objectJson;
    }


    public static void main(String[] args) {
        String message = "{\"header\":{\"@type\":\"ids:LogMessage\",\"@id\":\"https://w3id.org/idsa/autogen/logMessage/69dca368-8d1f-42e9-8e83-3b9447127f7b\",\"ids:securityToken\":null,\"ids:recipientAgent\":null,\"ids:authorizationToken\":null,\"ids:contentVersion\":null,\"ids:modelVersion\":null,\"ids:issued\":\"2020-12-09T11:50:36.929UTC\",\"ids:correlationMessage\":null,\"ids:issuerConnector\":\"auto-generated\",\"ids:recipientConnector\":null,\"ids:senderAgent\":null,\"ids:transferContract\":null},\"body\":{\"header\":{\"@type\":\"ids:ArtifactRequestMessage\",\"@id\":\"https://w3id.org/idsa/autogen/artifactRequestMessage/d148f1dd-8d2d-4f15-9fb8-665b7418042e\",\"ids:securityToken\":null,\"ids:recipientAgent\":null,\"ids:authorizationToken\":null,\"ids:contentVersion\":null,\"ids:modelVersion\":\"4.0.0\",\"ids:issued\":\"2020-12-09T11:50:19.465UTC\",\"ids:correlationMessage\":null,\"ids:issuerConnector\":\"http://true.engineering.it/ids/mdm-connector\",\"ids:recipientConnector\":null,\"ids:senderAgent\":null,\"ids:transferContract\":null,\"ids:requestedArtifact\":\"http://mdm-connector.ids.isst.fraunhofer.de/artifact/1\"},\"payload\":\"7a38bf81f383f69433ad6e900d35b3e2385593f76a7b7ab5d4355b8ba41ee24b\"}}";
        String data = removeTimezoneFromIssued(message);
        System.out.println(data);
    }
}
